### PR TITLE
Updates to conan 1.1, adds bincrafters libcurl

### PR DESCRIPTION
**Pull request by danimtb**
Hi @jonico!

This a PR to update your recipe to conan 1.1 version.
I have also added l[ibcurl library from the bincrafters](https://github.com/bincrafters/conan-libcurl) repository to update the old one from lasote that was outdated in conan-transit.

test_package is working well under Windows Visual Studio 15, but I have not checked other settings.

Please note I have NOT checked the CI files, so for CI  at the moment you would have to add the [bincrafters bintray repository](https://bintray.com/bincrafters/public-conan) to the conan-package-tools (If I have time a would add that to this PR as well).

If you need more help with this just ask me please 😄

### CODE REVIEW

**Comment by danimtb** [comment]
I will check the CI later to add the bincrafters repo! hold tight :)

**Comment by jonico** [comment]
@danimtb: Thanks a lot for your ✨ contributions, very much appreciated. Once CI ❤️ this repo again, I will have a deeper look into the details. Have you also checked whether https://github.com/jonico/zenofgithub is still working with the proposed changes?

**Comment by danimtb** [comment]
Still having a look to it. Currently working on libcurl dependency with libssh2 (cool library as well!). I will check the CI ASAP and let you know! 😺

**Comment by danimtb** [comment]
Seems Apple builds are failling due to missing packages for your predefined build options: https://github.com/jonico/libzengithub/blob/042deb4ab7bf752785c84041fa75b88ce9a1e650/build.py#L22. Those package options are quite specific and we dont make package authors generate all possibilities of the recipe as that would increase CI times a lot.

In case of Linux gcc 4.9, it was an issue from the docker image that should be solved now. Just relaunch the job and we'll see how it goes.

**Comment by jonico** [comment]
> Those package options are quite specific and we dont make package authors generate all possibilities of the recipe as that would increase CI times a lot.

The point of this example was to show how you can generate packages for as many permutations as possible 😊 

image


I would at least need some working example on how to build this on various Apple versions.

**Comment by danimtb** [comment]
I have been testing the CI configuration with options and to me the bes would be to let the `builder.add_common_builds()` include the "standard" build configurations.

I have generated a table just for Windows and Mac (Travis CI) and this is the result:

image

So the final table would also have the Windows builds in the matrix. Would you be fine with this result? I would add those changes to this PR if so 😊

**Comment by jonico** [comment]
@danimtb: This looks cool. I guess Windows builds would just come from AppVeyor which are currently not broken, so this would add to the table wouldn't it?

**Comment by danimtb** [comment]
Yes, definitely. Complete table with windows builds! I'll bring the changes to this PR

**Comment by danimtb** [comment]
Hi again @jonico!

Please have a look at the changes of this PR to check everything is fine :)

**Comment by jonico** [comment]
Hi @danimtb, just returned from vacation. I will mrge your PR after my demo next week in Böblingen as I like to avoid surprises at the big show 😊

**Pull request merged**
